from setuptools import setup

setup(name = 'dailyrotatingfilelogger',
    version = '0.0.1',
    url = 'https://github.com/borisliu/dailyrotatingfilelogger',
    license = 'MIT',
    author = 'borisliu',
    author_email = 'boris_cn@263.net',
    description = 'Rotating the log file every midnight.',
    platforms=['all'],
    classifiers=[
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.5',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.2',
        'Programming Language :: Python :: 3.3',
    ],
    py_modules=['dailyhandler'],
)